ALTER TABLE "Customer"
  ADD COLUMN "passwordChangedAt" TIMESTAMP(3);

ALTER TABLE "Address"
  ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_shippingAddressId_fkey";

ALTER TABLE "Order"
  ADD CONSTRAINT "Order_shippingAddressId_fkey"
  FOREIGN KEY ("shippingAddressId") REFERENCES "Address"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
