const nodemailer = require('nodemailer');
const prisma = require('../config/database');
const { recordAudit } = require('../utils/auditService');

const transporter = () => nodemailer.createTransport({ host: process.env.EMAIL_HOST, port: Number(process.env.EMAIL_PORT), secure: Number(process.env.EMAIL_PORT) === 465, auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS } });
const normalizePromotion = body => ({
  code: body.code?.trim().toUpperCase(), name: body.name?.trim(), discountType: body.discountType,
  value: Number(body.value), minimumOrder: body.minimumOrder ? Number(body.minimumOrder) : null,
  maximumDiscount: body.maximumDiscount ? Number(body.maximumDiscount) : null,
  usageLimit: body.usageLimit ? Number(body.usageLimit) : null, startsAt: body.startsAt ? new Date(body.startsAt) : null,
  endsAt: body.endsAt ? new Date(body.endsAt) : null, isActive: body.isActive !== false,
  categories: Array.isArray(body.categories) ? body.categories.map(String) : [], artworkIds: Array.isArray(body.artworkIds) ? body.artworkIds.map(String) : [],
});

exports.listPromotions = async (req,res) => res.json(await prisma.promotion.findMany({ orderBy:{ createdAt:'desc' } }));
exports.createPromotion = async (req,res) => { try { const data=normalizePromotion(req.body); if(!data.code||!data.name||!['PERCENTAGE','FIXED'].includes(data.discountType)||!(data.value>0)) return res.status(400).json({error:'Code, name, valid type and positive value are required'}); if(data.discountType==='PERCENTAGE'&&data.value>100) return res.status(400).json({error:'Percentage cannot exceed 100'}); const item=await prisma.promotion.create({data}); await recordAudit(req,'CREATE_PROMOTION','Promotion',item.id,{code:item.code}); res.status(201).json(item); } catch(error){ console.error(error); res.status(error.code==='P2002'?409:500).json({error:error.code==='P2002'?'Promotion code already exists':'Failed to create promotion'}); } };
exports.updatePromotion = async (req,res) => { try { const item=await prisma.promotion.update({where:{id:req.params.id},data:normalizePromotion(req.body)}); await recordAudit(req,'UPDATE_PROMOTION','Promotion',item.id,{code:item.code}); res.json(item); } catch(error){console.error(error);res.status(500).json({error:'Failed to update promotion'});} };
exports.deletePromotion = async (req,res) => { try { const item=await prisma.promotion.findUnique({where:{id:req.params.id}}); if(!item)return res.status(404).json({error:'Promotion not found'}); if(item.usageCount>0){await prisma.promotion.update({where:{id:item.id},data:{isActive:false}});return res.json({archived:true});} await prisma.promotion.delete({where:{id:item.id}}); await recordAudit(req,'DELETE_PROMOTION','Promotion',item.id,{code:item.code}); res.json({success:true}); } catch(error){res.status(500).json({error:'Failed to remove promotion'});} };
exports.validatePromotion = async (req,res) => { try { const code=req.body.code?.trim().toUpperCase(); const subtotal=Number(req.body.subtotal); const promotion=await prisma.promotion.findUnique({where:{code}}); const now=new Date(); if(!promotion||!promotion.isActive||(promotion.startsAt&&promotion.startsAt>now)||(promotion.endsAt&&promotion.endsAt<now)||(promotion.usageLimit&&promotion.usageCount>=promotion.usageLimit)) return res.status(400).json({error:'Promotion is not active'}); if(promotion.minimumOrder&&subtotal<Number(promotion.minimumOrder)) return res.status(400).json({error:`Minimum order is $${Number(promotion.minimumOrder).toLocaleString()}`}); if(promotion.artworkIds.length||promotion.categories.length){const artworks=await prisma.artwork.findMany({where:{id:{in:Array.isArray(req.body.artworkIds)?req.body.artworkIds:[]}},select:{id:true,category:true}});const eligible=(!promotion.artworkIds.length||artworks.some(a=>promotion.artworkIds.includes(a.id)))&&(!promotion.categories.length||artworks.some(a=>promotion.categories.includes(a.category)));if(!eligible)return res.status(400).json({error:'Promotion does not apply to these artworks'});} let discount=promotion.discountType==='PERCENTAGE'?subtotal*Number(promotion.value)/100:Number(promotion.value); if(promotion.maximumDiscount)discount=Math.min(discount,Number(promotion.maximumDiscount)); discount=Math.min(discount,subtotal); res.json({id:promotion.id,code:promotion.code,name:promotion.name,discount:Number(discount.toFixed(2)),total:Number((subtotal-discount).toFixed(2))}); } catch(error){res.status(500).json({error:'Failed to validate promotion'});} };

exports.listTemplates = async(req,res)=>res.json(await prisma.emailTemplate.findMany({orderBy:{updatedAt:'desc'}}));
exports.saveTemplate = async(req,res)=>{try{const data={name:req.body.name?.trim(),subject:req.body.subject?.trim(),htmlBody:req.body.htmlBody};if(!data.name||!data.subject||!data.htmlBody)return res.status(400).json({error:'Name, subject and body are required'});const item=req.params.id?await prisma.emailTemplate.update({where:{id:req.params.id},data}):await prisma.emailTemplate.create({data});await recordAudit(req,req.params.id?'UPDATE_EMAIL_TEMPLATE':'CREATE_EMAIL_TEMPLATE','EmailTemplate',item.id,{name:item.name});res.json(item);}catch(error){res.status(500).json({error:'Failed to save template'});}};
exports.testEmail = async(req,res)=>{try{if(!req.body.email||!req.body.subject||!req.body.htmlBody)return res.status(400).json({error:'Email, subject and body are required'});await transporter().sendMail({from:`"Highmarc" <${process.env.EMAIL_USER}>`,to:req.body.email,subject:`[TEST] ${req.body.subject}`,html:req.body.htmlBody});await recordAudit(req,'SEND_TEST_EMAIL','EmailTemplate',null,{email:req.body.email});res.json({success:true});}catch(error){console.error(error);res.status(502).json({error:'Test email could not be delivered'});}};
exports.listCampaigns = async(req,res)=>res.json(await prisma.emailCampaign.findMany({orderBy:{createdAt:'desc'}}));
exports.createCampaign = async(req,res)=>{try{const data={name:req.body.name?.trim(),subject:req.body.subject?.trim(),htmlBody:req.body.htmlBody,segment:req.body.segment||'VERIFIED'};if(!data.name||!data.subject||!data.htmlBody)return res.status(400).json({error:'Name, subject and body are required'});const item=await prisma.emailCampaign.create({data});await recordAudit(req,'CREATE_EMAIL_CAMPAIGN','EmailCampaign',item.id,{name:item.name,segment:item.segment});res.status(201).json(item);}catch(error){res.status(500).json({error:'Failed to create campaign'});}};
exports.sendCampaign = async(req,res)=>{try{const campaign=await prisma.emailCampaign.findUnique({where:{id:req.params.id}});if(!campaign)return res.status(404).json({error:'Campaign not found'});if(campaign.status==='SENT')return res.status(409).json({error:'Campaign has already been sent'});const where={isSuspended:false,...(campaign.segment==='VERIFIED'?{isVerified:true}:campaign.segment==='CUSTOMERS'?{orders:{some:{paymentStatus:'FULLY_PAID'}}}:campaign.segment==='COMMISSION_CLIENTS'?{commissions:{some:{paymentStatus:{in:['DEPOSIT_PAID','FULLY_PAID']}}}}:{})};const recipients=await prisma.customer.findMany({where,select:{email:true,firstName:true},take:500});let delivered=0,failed=0;for(const recipient of recipients){try{await transporter().sendMail({from:`"Highmarc" <${process.env.EMAIL_USER}>`,to:recipient.email,subject:campaign.subject,html:campaign.htmlBody.replaceAll('{{firstName}}',recipient.firstName||'there')});delivered++;}catch{failed++;}}const item=await prisma.emailCampaign.update({where:{id:campaign.id},data:{status:failed?'SENT_WITH_ERRORS':'SENT',recipientCount:recipients.length,deliveredCount:delivered,failedCount:failed,sentAt:new Date()}});await recordAudit(req,'SEND_EMAIL_CAMPAIGN','EmailCampaign',item.id,{recipients:recipients.length,delivered,failed});res.json(item);}catch(error){console.error(error);res.status(500).json({error:'Campaign delivery failed'});}};
