import { createElement, useCallback, useEffect, useState } from 'react';
import { BadgePercent, Mail, Megaphone, Bell, Loader, Send, Plus, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { marketingAPI, notificationsAPI } from '../../services/api';

const blankPromotion={code:'',name:'',discountType:'PERCENTAGE',value:'',minimumOrder:'',maximumDiscount:'',usageLimit:'',startsAt:'',endsAt:'',isActive:true,categories:[],artworkIds:[]};
const blankEmail={name:'',subject:'',htmlBody:'<p>Hello {{firstName}},</p><p></p>',segment:'VERIFIED'};
export default function Marketing(){
 const [tab,setTab]=useState('promotions'),[loading,setLoading]=useState(true),[promotions,setPromotions]=useState([]),[templates,setTemplates]=useState([]),[campaigns,setCampaigns]=useState([]);const [promotion,setPromotion]=useState(blankPromotion),[template,setTemplate]=useState(blankEmail),[campaign,setCampaign]=useState(blankEmail),[testEmail,setTestEmail]=useState(''),[notification,setNotification]=useState({type:'SYSTEM',message:'',link:''}),[sending,setSending]=useState('');
 const load=useCallback(async()=>{try{setLoading(true);const[p,t,c]=await Promise.all([marketingAPI.getPromotions(),marketingAPI.getTemplates(),marketingAPI.getCampaigns()]);setPromotions(p.data);setTemplates(t.data);setCampaigns(c.data);}catch{toast.error('Failed to load marketing tools');}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 const savePromotion=async()=>{try{promotion.id?await marketingAPI.updatePromotion(promotion.id,promotion):await marketingAPI.createPromotion(promotion);toast.success('Promotion saved');setPromotion(blankPromotion);load();}catch(error){toast.error(error.response?.data?.error||'Promotion failed');}};
 const removePromotion=async id=>{if(!confirm('Remove this promotion? Used promotions will be deactivated instead.'))return;try{await marketingAPI.deletePromotion(id);toast.success('Promotion removed');load();}catch{toast.error('Could not remove promotion');}};
 const saveTemplate=async()=>{try{template.id?await marketingAPI.updateTemplate(template.id,template):await marketingAPI.saveTemplate(template);toast.success('Template saved');setTemplate(blankEmail);load();}catch(error){toast.error(error.response?.data?.error||'Template failed');}};
 const sendTest=async()=>{try{setSending('test');await marketingAPI.testEmail({email:testEmail,subject:template.subject,htmlBody:template.htmlBody});toast.success('Test email delivered');}catch(error){toast.error(error.response?.data?.error||'Test failed');}finally{setSending('');}};
 const createCampaign=async()=>{try{await marketingAPI.createCampaign(campaign);toast.success('Campaign saved as draft');setCampaign(blankEmail);load();}catch(error){toast.error(error.response?.data?.error||'Campaign failed');}};
 const sendCampaign=async item=>{if(!confirm(`Send “${item.name}” to ${item.segment.toLowerCase()} customers now?`))return;try{setSending(item.id);const{data}=await marketingAPI.sendCampaign(item.id);toast.success(`Delivered ${data.deliveredCount}; failed ${data.failedCount}`);load();}catch(error){toast.error(error.response?.data?.error||'Delivery failed');}finally{setSending('');}};
 const createNotification=async()=>{try{await notificationsAPI.create(notification);toast.success('Admin notification created');setNotification({type:'SYSTEM',message:'',link:''});}catch(error){toast.error(error.response?.data?.error||'Notification failed');}};
 if(loading)return <Loader className="animate-spin m-16 mx-auto"/>;const tabs=[['promotions',BadgePercent,'Promotions'],['templates',Mail,'Templates'],['campaigns',Megaphone,'Campaigns'],['notifications',Bell,'Notifications']];
 return <div className="space-y-6"><div><h1 className="text-2xl font-serif">Marketing & Communications</h1><p className="text-stone-500">Discounts, reusable email content, campaigns and admin alerts.</p></div><div className="flex gap-2 overflow-x-auto">{tabs.map(([key,icon,text])=><button key={key} onClick={()=>setTab(key)} className={`inline-flex gap-2 items-center px-4 py-2 rounded-lg ${tab===key?'bg-stone-900 text-white':'bg-white border'}`}>{createElement(icon,{size:16})}{text}</button>)}</div>
 {tab==='promotions'&&<div className="grid lg:grid-cols-2 gap-5"><Panel title="Create or edit promotion"><div className="grid grid-cols-2 gap-3"><Input label="Code" value={promotion.code} onChange={code=>setPromotion({...promotion,code:code.toUpperCase()})}/><Input label="Name" value={promotion.name} onChange={name=>setPromotion({...promotion,name})}/><Select label="Type" value={promotion.discountType} onChange={discountType=>setPromotion({...promotion,discountType})} options={['PERCENTAGE','FIXED']}/><Input label="Value" type="number" value={promotion.value} onChange={value=>setPromotion({...promotion,value})}/><Input label="Minimum order" type="number" value={promotion.minimumOrder} onChange={minimumOrder=>setPromotion({...promotion,minimumOrder})}/><Input label="Maximum discount" type="number" value={promotion.maximumDiscount} onChange={maximumDiscount=>setPromotion({...promotion,maximumDiscount})}/><Input label="Usage limit" type="number" value={promotion.usageLimit} onChange={usageLimit=>setPromotion({...promotion,usageLimit})}/><label className="text-sm flex items-end gap-2 pb-3"><input type="checkbox" checked={promotion.isActive} onChange={e=>setPromotion({...promotion,isActive:e.target.checked})}/>Active</label><Input label="Starts" type="datetime-local" value={promotion.startsAt?.slice?.(0,16)||''} onChange={startsAt=>setPromotion({...promotion,startsAt})}/><Input label="Ends" type="datetime-local" value={promotion.endsAt?.slice?.(0,16)||''} onChange={endsAt=>setPromotion({...promotion,endsAt})}/></div><button onClick={savePromotion} className="bg-stone-900 text-white px-4 py-2 rounded-lg">Save promotion</button></Panel><Panel title="Promotion codes">{promotions.map(item=><div key={item.id} className="border rounded-lg p-3 flex justify-between mb-2"><button onClick={()=>setPromotion({...item,startsAt:item.startsAt||'',endsAt:item.endsAt||''})} className="text-left"><b>{item.code}</b><p className="text-xs text-stone-500">{item.discountType==='PERCENTAGE'?`${Number(item.value)}%`:`$${Number(item.value)}`} · {item.usageCount} uses · {item.isActive?'Active':'Inactive'}</p></button><button onClick={()=>removePromotion(item.id)} className="text-red-600"><Trash2 size={16}/></button></div>)}</Panel></div>}
 {tab==='templates'&&<div className="grid lg:grid-cols-2 gap-5"><EmailEditor title="Email template" value={template} setValue={setTemplate}/><Panel title="Saved templates">{templates.map(item=><button key={item.id} onClick={()=>setTemplate(item)} className="block w-full text-left border rounded-lg p-3 mb-2"><b>{item.name}</b><p className="text-xs text-stone-500">{item.subject}</p></button>)}<button onClick={saveTemplate} className="mt-3 bg-stone-900 text-white px-4 py-2 rounded-lg">Save template</button><div className="flex gap-2 mt-4"><input value={testEmail} onChange={e=>setTestEmail(e.target.value)} placeholder="Test recipient" className="border rounded-lg px-3 flex-1"/><button onClick={sendTest} disabled={sending==='test'} className="border px-3 rounded-lg">Send test</button></div></Panel></div>}
 {tab==='campaigns'&&<div className="grid lg:grid-cols-2 gap-5"><div><EmailEditor title="New campaign" value={campaign} setValue={setCampaign}/><Select label="Recipient segment" value={campaign.segment} onChange={segment=>setCampaign({...campaign,segment})} options={['VERIFIED','ALL','CUSTOMERS','COMMISSION_CLIENTS']}/><button onClick={createCampaign} className="bg-stone-900 text-white px-4 py-2 rounded-lg"><Plus size={15} className="inline"/> Save draft</button></div><Panel title="Campaign delivery">{campaigns.map(item=><div key={item.id} className="border rounded-lg p-3 mb-2"><div className="flex justify-between"><div><b>{item.name}</b><p className="text-xs text-stone-500">{item.segment} · {item.status}</p></div>{item.status==='DRAFT'&&<button onClick={()=>sendCampaign(item)} disabled={sending===item.id} className="text-amber-700"><Send size={17}/></button>}</div>{item.status!=='DRAFT'&&<p className="text-xs mt-2">Delivered {item.deliveredCount}/{item.recipientCount} · Failed {item.failedCount}</p>}</div>)}</Panel></div>}
 {tab==='notifications'&&<Panel title="Create an admin notification"><Select label="Type" value={notification.type} onChange={type=>setNotification({...notification,type})} options={['SYSTEM','ORDER','COMMISSION','MARKETING']}/><Input label="Message" value={notification.message} onChange={message=>setNotification({...notification,message})}/><Input label="Optional admin link" value={notification.link} onChange={link=>setNotification({...notification,link})}/><button onClick={createNotification} className="bg-stone-900 text-white px-4 py-2 rounded-lg">Create notification</button></Panel>}</div>;
}
const Panel=({title,children})=><section className="bg-white border rounded-xl p-5"><h2 className="font-semibold mb-4">{title}</h2>{children}</section>;
const Input=({label,type='text',value,onChange})=><label className="block text-sm mb-3">{label}<input type={type} value={value||''} onChange={e=>onChange(e.target.value)} className="block w-full border rounded-lg px-3 py-2 mt-1"/></label>;
const Select=({label,value,onChange,options})=><label className="block text-sm mb-3">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="block w-full border rounded-lg px-3 py-2 mt-1">{options.map(item=><option key={item}>{item}</option>)}</select></label>;
const EmailEditor=({title,value,setValue})=><Panel title={title}><Input label="Internal name" value={value.name} onChange={name=>setValue({...value,name})}/><Input label="Subject" value={value.subject} onChange={subject=>setValue({...value,subject})}/><label className="text-sm">HTML body (supports {'{{firstName}}'})<textarea rows="10" value={value.htmlBody} onChange={e=>setValue({...value,htmlBody:e.target.value})} className="block w-full font-mono text-xs border rounded-lg p-3 mt-1"/></label></Panel>;
