import { createElement, useCallback, useEffect, useState } from 'react';
import { DollarSign, ShoppingBag, Palette, Receipt, WalletCards, Download, Loader, TrendingUp, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { reportsAPI } from '../../services/api';

const iso=date=>date.toISOString().slice(0,10);const money=value=>`$${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function Reports(){
 const today=new Date(),monthAgo=new Date(today.getTime()-29*86400000);const[dates,setDates]=useState({from:iso(monthAgo),to:iso(today)}),[data,setData]=useState(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{setLoading(true);const response=await reportsAPI.getFinancial(dates);setData(response.data);}catch(error){toast.error(error.response?.data?.error||'Report failed');}finally{setLoading(false);}},[dates]);useEffect(()=>{load();},[load]);
 const exportCsv=async()=>{try{const{data:blob}=await reportsAPI.exportFinancial(dates);const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`financial-report-${dates.from}-${dates.to}.csv`;anchor.click();URL.revokeObjectURL(url);}catch{toast.error('Export failed');}};
 if(loading&&!data)return <Loader className="animate-spin m-16 mx-auto"/>;const summary=data?.summary||{};const cards=[[DollarSign,'Net revenue',money(summary.netRevenue)],[ShoppingBag,'Artwork revenue',money(summary.orderRevenue)],[Palette,'Commission revenue',money(summary.commissionRevenue)],[Receipt,'Discounts',money(summary.discounts)],[WalletCards,'Outstanding',money(summary.outstanding)],[TrendingUp,'Average order',money(summary.averageOrderValue)]];const max=Math.max(...(data?.revenueByDay||[]).map(item=>item.total),1);
 return <div className="space-y-6"><div className="flex flex-col lg:flex-row justify-between gap-3"><div><h1 className="text-2xl font-serif">Financial Reports</h1><p className="text-stone-500">Paid revenue, discounts, refunds and outstanding commission balances.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={dates.from} onChange={e=>setDates({...dates,from:e.target.value})} className="border rounded-lg px-3 py-2"/><input type="date" value={dates.to} onChange={e=>setDates({...dates,to:e.target.value})} className="border rounded-lg px-3 py-2"/><button onClick={exportCsv} className="bg-stone-900 text-white rounded-lg px-4 py-2 inline-flex gap-2 items-center"><Download size={16}/>Export</button></div></div>
 <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-3">{cards.map(([icon,label,value])=><div key={label} className="bg-white border rounded-xl p-4">{createElement(icon,{size:17,className:'text-amber-700'})}<p className="text-xs text-stone-500 mt-2">{label}</p><p className="text-xl font-bold">{value}</p></div>)}</div>
 <section className="bg-white border rounded-xl p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Revenue trend</h2><p className="text-xs text-stone-500">Artwork and commission cash received</p></div><b>{money(summary.grossRevenue)}</b></div><div className="h-44 flex items-end gap-1 mt-5">{data?.revenueByDay?.length?data.revenueByDay.map(item=><div key={item.date} title={`${item.date}: ${money(item.total)}`} className="flex-1 min-w-1 bg-amber-500 hover:bg-amber-600 rounded-t" style={{height:`${Math.max(3,item.total/max*100)}%`}}/>):<p className="m-auto text-stone-400 text-sm">No paid transactions in this range.</p>}</div></section>
 <div className="grid lg:grid-cols-2 gap-5"><Table title="Top artworks" headers={['Artwork','Sales','Revenue']} rows={(data?.topArtworks||[]).map(item=>[item.title,item.sales,money(item.revenue)])}/><Table title="Top customers" icon={Users} headers={['Customer','Orders','Revenue']} rows={(data?.topCustomers||[]).map(item=>[<span key={item.id}>{item.name}<small className="block text-stone-400">{item.email}</small></span>,item.orders,money(item.revenue)])}/></div>
 <div className="grid lg:grid-cols-2 gap-5"><Table title="Promotion usage" headers={['Code','Uses','Value']} rows={(data?.promotions||[]).map(item=>[item.code,item.usageCount,item.type==='PERCENTAGE'?`${item.value}%`:money(item.value)])}/><Table title="Commission receivables" headers={['Commission','Customer','Due']} rows={(data?.receivables||[]).map(item=>[<span key={item.id}>{item.commissionNumber}<small className="block text-stone-400">{item.paymentStatus.replaceAll('_',' ')}</small></span>,item.customer,money(item.amountDue)])}/></div>
 <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-900">Revenue includes only fully paid orders and commission deposits/balances whose payment dates fall inside the selected range. Outstanding balances are shown separately and are not counted as revenue.</div></div>;
}
const Table=({title,headers,rows})=><section className="bg-white border rounded-xl overflow-hidden"><h2 className="font-semibold p-5 border-b">{title}</h2>{rows.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50"><tr>{headers.map(item=><th key={item} className="text-left px-4 py-2">{item}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t">{row.map((cell,i)=><td key={i} className="px-4 py-3">{cell}</td>)}</tr>)}</tbody></table></div>:<p className="p-8 text-center text-stone-400 text-sm">No data in this period.</p>}</section>;
